name: Setup Tailscale as Exit Node

on:
  workflow_dispatch:  
  schedule:
    - cron: '5 */5 * * *'

jobs:
  install-tailscale:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Tailscale GPG Key and Repo
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

      - name: Enable IP Forwarding
        run: |
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          sudo sysctl -p /etc/sysctl.d/99-tailscale.conf

      - name: Install Tailscale
        run: |
          sudo apt-get update
          sudo apt-get install -y tailscale

      - name: Start Tailscale (requires authkey)
        run: |
          sudo tailscale up --authkey=${{ secrets.TS_AUTHKEY }} --advertise-exit-node --hostname=github-exit-node

      - name: Show Tailscale IP
        run: tailscale ip -4

      - name: Keep Job Running
        run: |
          echo "Tailscale is running. Keeping GitHub Actions job alive..."
          tail -f /dev/null
